name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Use .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
      - name: Building
        run: dotnet build MathCore.WPF.MAP -c Release --nologo
        
      - name: Packing
        run: dotnet pack MathCore.WPF.MAP --no-build -c Release -v q --nologo
        
      - name: Publishing NuGet
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetApiKey }}
        
      - name: Publishing GitHub
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/Infarh/index.json -k ${{secrets.GITHUB_TOKEN}}
